FROM node:14

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install production dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Build your React app
RUN npm run build

# Expose the port your app will run on (usually 3000)
EXPOSE 3000

# Start your app
CMD ["npm", "start"]